<a href="https://colab.research.google.com/github/ankurdev1-drth/Deep_Learning-/blob/main/02_Training_Deep_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

In [1]:
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import torch

layer = nn.Linear(40, 10)
layer.weight.data *= 6 ** 0.5  # kaiming init (or 3 ** 0.5 for LeCun)
torch.zero_(layer.bias.data)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
layer.weight.shape

torch.Size([10, 40])

In [4]:
layer.bias.shape

torch.Size([10])

In [5]:
# another way to for initialization
nn.init.kaiming_uniform_(layer.weight)
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

This is clearer and less error prone as compared to the first approach

For applying initialization to the weights of every `nn.Linear` layer in a model the simples option is to write a little function that takes a module, checks whether it's an instance of the `nn.Linear` class, and if so , applies the desired initialization function to its weights. and the function can be then applied using the `apply()` method

In [6]:
def use_he_init(module):
  if isinstance(module, nn.Linear):
    nn.init.kaiming_uniform_(module.weight)
    nn.init.zeros_(module.bias)

module = nn.Sequential(
    nn.Linear(40, 10),
    nn.ReLU(),
    nn.Linear(10, 1),
    nn.ReLU()
    )
module.apply(use_he_init)

Sequential(
  (0): Linear(in_features=40, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
  (3): ReLU()
)

### Leaky ReLU

In [7]:
alpha = 0.2
model = nn.Sequential(
    nn.Linear(50, 40), #0
    nn.LeakyReLU(negative_slope=alpha), #1
    nn.Linear(40, 20), #2
    nn.LeakyReLU(negative_slope=alpha) #3

)
nn.init.kaiming_uniform_(model[0].weight, alpha,
nonlinearity="leaky_relu")
nn.init.kaiming_uniform_(model[2].weight, alpha,nonlinearity="leaky_relu")

Parameter containing:
tensor([[ 2.5594e-01,  3.2266e-02, -3.1998e-01, -2.5836e-01,  3.4588e-01,
          3.4004e-01, -8.5409e-02, -8.7054e-02, -1.1318e-01, -2.1986e-01,
          2.0346e-01,  2.2373e-01,  1.7150e-01, -1.4364e-01,  6.5490e-02,
          3.1379e-01,  2.3368e-01,  2.2908e-01,  2.0824e-01,  1.3219e-01,
          1.6211e-01,  1.7078e-01,  8.2473e-02, -2.7260e-01,  2.5180e-01,
          1.5429e-01, -2.2898e-01, -4.7352e-02, -2.6561e-01,  1.0389e-01,
         -3.0682e-01, -6.5872e-02,  1.7435e-01, -2.2374e-01,  3.5253e-01,
          3.0050e-01, -1.0470e-01,  3.2609e-01, -2.2713e-01,  8.5222e-02],
        [-1.8160e-01, -3.0647e-01,  2.0729e-03,  1.5036e-01, -1.7886e-01,
         -1.2299e-01,  2.4857e-01,  9.3504e-02,  2.9631e-01,  2.1883e-01,
          8.7430e-03,  1.6548e-01,  9.7834e-02,  2.4677e-01, -2.3144e-01,
          1.8754e-01, -1.3917e-01, -3.2190e-01,  2.1640e-01, -2.4992e-01,
         -2.0699e-01, -2.0561e-01, -2.2115e-01,  1.0969e-02,  3.2112e-01,
         -2.029

### ELU and SELU