<a href="https://colab.research.google.com/github/ankurdev1-drth/Deep_Learning-/blob/main/02_Training_Deep_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

In [27]:
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
import torch

layer = nn.Linear(40, 10)
layer.weight.data *= 6 ** 0.5  # kaiming init (or 3 ** 0.5 for LeCun)
torch.zero_(layer.bias.data)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
layer.weight.shape

torch.Size([10, 40])

torch.Size([10, 40])

In [30]:
layer.bias.shape

torch.Size([10])

torch.Size([10])

In [31]:
# another way to for initialization
nn.init.kaiming_uniform_(layer.weight)
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

This is clearer and less error prone as compared to the first approach

For applying initialization to the weights of every `nn.Linear` layer in a model the simples option is to write a little function that takes a module, checks whether it's an instance of the `nn.Linear` class, and if so , applies the desired initialization function to its weights. and the function can be then applied using the `apply()` method

In [32]:
def use_he_init(module):
  if isinstance(module, nn.Linear):
    nn.init.kaiming_uniform_(module.weight)
    nn.init.zeros_(module.bias)

module = nn.Sequential(
    nn.Linear(40, 10),
    nn.ReLU(),
    nn.Linear(10, 1),
    nn.ReLU()
    )
module.apply(use_he_init)

Sequential(
  (0): Linear(in_features=40, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
  (3): ReLU()
)

Sequential(
  (0): Linear(in_features=40, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
  (3): ReLU()
)

### Leaky ReLU

In [33]:
alpha = 0.2
model = nn.Sequential(
    nn.Linear(50, 40), #0
    nn.LeakyReLU(negative_slope=alpha), #1
    nn.Linear(40, 20), #2
    nn.LeakyReLU(negative_slope=alpha) #3

)
nn.init.kaiming_uniform_(model[0].weight, alpha,
nonlinearity="leaky_relu")
nn.init.kaiming_uniform_(model[2].weight, alpha,nonlinearity="leaky_relu")

Parameter containing:
tensor([[-0.1578, -0.3148,  0.1519, -0.3620, -0.0323, -0.1706,  0.1349,  0.2953,
          0.1029,  0.1731, -0.1705, -0.3556,  0.0240,  0.0033, -0.2403,  0.0135,
         -0.1823, -0.2401,  0.1568,  0.3371,  0.0784,  0.2876,  0.0783, -0.3547,
          0.1184, -0.0917, -0.3769, -0.0082, -0.2893, -0.1759,  0.2909, -0.3562,
         -0.0400,  0.3059,  0.1749, -0.0427,  0.3035,  0.0378,  0.3000, -0.3313],
        [ 0.3214,  0.0872,  0.2352,  0.2640,  0.2440, -0.3262,  0.1309, -0.0709,
          0.3537, -0.0281, -0.0772,  0.2564,  0.1771,  0.0124, -0.2524,  0.2475,
         -0.1437, -0.0292,  0.0592, -0.2008, -0.3238, -0.2443,  0.2074, -0.1617,
         -0.0950, -0.1724, -0.1175,  0.3455,  0.2958,  0.1214, -0.0407, -0.0577,
         -0.3035, -0.0497, -0.2668,  0.3525, -0.3165, -0.3778,  0.0754, -0.0145],
        [-0.3130, -0.1689, -0.2299, -0.2491, -0.3238, -0.2101, -0.0506, -0.3046,
         -0.0739,  0.0630, -0.0710,  0.0491, -0.0606, -0.1459, -0.2176,  0.3115,
    

Parameter containing:
tensor([[-1.6810e-01, -1.5817e-01, -2.8925e-01,  3.5427e-01, -2.1457e-01,
         -1.7087e-01, -1.1507e-01,  3.1970e-01,  1.7717e-01,  1.3983e-01,
         -9.9867e-02,  1.9193e-01,  6.8893e-02,  3.0259e-01,  8.4308e-02,
          2.7874e-01,  2.6209e-01,  6.6366e-02, -3.6393e-01,  7.7273e-02,
         -2.8654e-01,  6.5249e-02, -4.2530e-02,  3.0218e-01, -2.7260e-01,
         -3.1750e-01,  1.6927e-01,  2.5075e-01, -8.2656e-02,  1.0279e-01,
          3.0479e-01,  3.7778e-02, -1.0615e-01,  2.1959e-01,  3.4228e-01,
         -6.4464e-02,  2.5768e-01,  3.1686e-02, -7.9520e-02, -3.3145e-02],
        [-3.6868e-01,  1.8219e-01, -2.0671e-01, -3.2344e-01, -5.2653e-02,
         -1.5473e-01, -2.4173e-01, -7.9954e-02, -4.0082e-02,  1.1543e-01,
          5.2052e-02, -5.0742e-02,  8.3600e-02, -2.4573e-01,  3.2135e-01,
          1.8596e-01,  2.4026e-01, -3.3874e-01,  2.5923e-01,  6.7131e-02,
         -3.6700e-01,  3.6061e-01, -7.9475e-03,  7.2835e-02,  3.1419e-01,
          2.449

### Batch Normalization

In [34]:
model = nn.Sequential(
    nn.Flatten(),
    nn.BatchNorm1d(1 * 28 * 28),
    nn.Linear(1 * 28 * 28,  300),
    nn.ReLU(),
    nn.BatchNorm1d(300),
    nn.Linear(300, 100),
    nn.ReLU(),
    nn.BatchNorm1d(100),
    nn.Linear(100, 10)
)

In [35]:
dict(model[1].named_parameters()).keys()

dict_keys(['weight', 'bias'])

dict_keys(['weight', 'bias'])

In [36]:
dict(model[1].named_buffers()).keys()

dict_keys(['running_mean', 'running_var', 'num_batches_tracked'])

dict_keys(['running_mean', 'running_var', 'num_batches_tracked'])

In [37]:
dict(model[1].named_children()).keys()

dict_keys([])

dict_keys([])

In [38]:
dict(model[1].named_modules()).keys()

dict_keys([''])

dict_keys([''])

Note:
- if BN layers before the activation functions, we can also remove the bias term from the previous `nn.Linear` layers by setting the `bias` hyperparameter to `False`.

In [39]:
Model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(1 * 28 * 28, 300, bias=False),
    nn.BatchNorm1d(300),
    nn.ReLU(),
    nn.Linear(300, 100, bias=False),
    nn.BatchNorm1d(100),
    nn.ReLU(),
    nn.Linear(100, 10)
)

### Layer Normalization

In [40]:
inputs = torch.randn(32, 3, 100, 200)   # batch of random RGB images
layer_norm = nn.LayerNorm([100, 200])
result = layer_norm(inputs)
result

tensor([[[[-1.4729e+00,  1.9399e+00,  9.6713e-01,  ..., -1.9172e+00,
            6.1512e-01, -7.1676e-01],
          [ 3.6040e-01,  5.7051e-01,  9.7976e-01,  ..., -4.4182e-01,
           -1.6680e-01,  1.3102e+00],
          [ 6.3419e-01, -6.5255e-01, -2.1532e+00,  ...,  7.8070e-02,
           -7.5205e-01, -2.0415e+00],
          ...,
          [-3.8249e-01, -6.6205e-01, -1.1210e-01,  ..., -2.0059e+00,
           -1.4229e+00,  1.4664e+00],
          [ 7.6240e-02,  2.1316e-01,  1.3446e+00,  ..., -2.0555e-01,
            1.3050e+00, -3.8872e-01],
          [-7.0612e-01,  3.1245e-01, -1.2421e+00,  ...,  3.5192e-01,
           -1.1358e-01,  8.9863e-01]],

         [[ 3.7716e-01, -5.0454e-01, -9.6019e-01,  ..., -5.4732e-01,
            1.7955e+00, -4.6952e-01],
          [ 1.0953e+00, -1.0116e+00, -8.6705e-02,  ...,  1.0937e+00,
            1.2918e-01,  4.2324e-02],
          [-1.5127e-01,  4.3457e-01, -1.6558e+00,  ...,  6.3859e-02,
            1.3250e+00,  9.8621e-01],
          ...,
     

tensor([[[[-7.5443e-01, -9.4642e-01,  1.9696e+00,  ...,  2.4618e-01,
            1.8509e+00,  6.8524e-02],
          [ 3.1707e-01,  2.0016e-01,  1.2113e+00,  ..., -4.6240e-01,
           -2.5169e-02, -6.0611e-01],
          [-2.7462e-02,  9.0097e-01,  6.7820e-01,  ..., -1.0042e+00,
            1.9947e-01, -2.4058e-01],
          ...,
          [ 3.0795e-01, -2.2038e-01, -1.4754e+00,  ...,  6.9433e-01,
           -4.3808e-01, -1.1435e+00],
          [-8.5028e-01, -2.6600e-01, -9.3852e-01,  ...,  6.3568e-01,
           -1.5122e-01,  1.7503e-01],
          [-1.1764e+00, -6.1199e-01,  1.0677e+00,  ...,  6.2375e-01,
            9.5664e-01,  7.6200e-01]],

         [[-2.0315e+00, -1.1363e+00, -1.1425e+00,  ...,  1.3318e+00,
           -1.3016e+00,  5.3877e-01],
          [ 7.8433e-02, -1.0333e+00, -1.7780e-01,  ...,  6.3204e-02,
            7.8275e-01,  2.5809e-01],
          [-1.0518e+00, -1.5114e+00,  1.4841e+00,  ...,  1.2439e+00,
           -6.9263e-01,  1.0199e+00],
          ...,
     

In [41]:
# method 2 to perform the same thing as above!
means = inputs.mean(dim=[2,3], keepdim=True)  #shape [32, 3, 1, 1]
vars_ = inputs.var(dim=[2,3], keepdim=True, unbiased=False) # shape: same
stds = torch.sqrt(vars_ + layer_norm.eps) # eps is a smoothing term (1e-5)
result = layer_norm.weight * (inputs - means) / stds + layer_norm.bias

In [42]:
layer_norm = nn.LayerNorm([3, 100, 200])
result = layer_norm(inputs)

In [43]:
result

tensor([[[[-1.4675e+00,  1.9439e+00,  9.7150e-01,  ..., -1.9116e+00,
            6.1965e-01, -7.1167e-01],
          [ 3.6503e-01,  5.7505e-01,  9.8413e-01,  ..., -4.3685e-01,
           -1.6195e-01,  1.3145e+00],
          [ 6.3870e-01, -6.4749e-01, -2.1475e+00,  ...,  8.2819e-02,
           -7.4695e-01, -2.0359e+00],
          ...,
          [-3.7755e-01, -6.5699e-01, -1.0727e-01,  ..., -2.0003e+00,
           -1.4175e+00,  1.4705e+00],
          [ 8.0990e-02,  2.1785e-01,  1.3488e+00,  ..., -2.0068e-01,
            1.3092e+00, -3.8378e-01],
          [-7.0104e-01,  3.1710e-01, -1.2368e+00,  ...,  3.5655e-01,
           -1.0875e-01,  9.0303e-01]],

         [[ 3.7212e-01, -5.0995e-01, -9.6579e-01,  ..., -5.5275e-01,
            1.7910e+00, -4.7491e-01],
          [ 1.0906e+00, -1.0173e+00, -9.1937e-02,  ...,  1.0890e+00,
            1.2404e-01,  3.7147e-02],
          [-1.5653e-01,  4.2956e-01, -1.6617e+00,  ...,  5.8691e-02,
            1.3204e+00,  9.8143e-01],
          ...,
     

tensor([[[[-7.5032e-01, -9.4185e-01,  1.9673e+00,  ...,  2.4794e-01,
            1.8489e+00,  7.0702e-02],
          [ 3.1867e-01,  2.0203e-01,  1.2108e+00,  ..., -4.5897e-01,
           -2.2771e-02, -6.0234e-01],
          [-2.5058e-02,  9.0119e-01,  6.7895e-01,  ..., -9.9950e-01,
            2.0134e-01, -2.3768e-01],
          ...,
          [ 3.0957e-01, -2.1753e-01, -1.4696e+00,  ...,  6.9504e-01,
           -4.3471e-01, -1.1385e+00],
          [-8.4594e-01, -2.6304e-01, -9.3398e-01,  ...,  6.3653e-01,
           -1.4852e-01,  1.7696e-01],
          [-1.1713e+00, -6.0821e-01,  1.0675e+00,  ...,  6.2462e-01,
            9.5673e-01,  7.6255e-01]],

         [[-2.0314e+00, -1.1376e+00, -1.1438e+00,  ...,  1.3265e+00,
           -1.3026e+00,  5.3476e-01],
          [ 7.5160e-02, -1.0347e+00, -1.8066e-01,  ...,  5.9955e-02,
            7.7835e-01,  2.5453e-01],
          [-1.0532e+00, -1.5121e+00,  1.4786e+00,  ...,  1.2388e+00,
           -6.9467e-01,  1.0151e+00],
          ...,
     

## Gradient Clipping

See the line nn.utils.clip_grad_norm_(...) in the training function in the next section.

# Reusing Pretrained Layers

### Transfer Learning with PyTorch

- X_train_A = images of all items except for T-shirts/tops and pullovers (classes 0 and 2 )
- X_train_B = first 20 images of Tshirt and Pullovers

The validation set and the test set are also split this way, but without restricting the number of images.

We will train a model on set A (classification task with 8 classes), and try to reuse it to tackle set B (binary classification). We hope to transfer a little bit of knowledge from task A to task B, since classes in set A (trousers, dresses, coats, sandals, shirts, sneakers, bags, and ankle boots) are somewhat similar to classes in set B (T-shirts/tops and pullovers). However, since we are using Linear layers, only patterns that occur at the same location can be reused (in contrast, convolutional layers will transfer much better, since learned patterns can be detected anywhere on the image)


In [44]:
from torch.utils.data import TensorDataset, DataLoader
from sklearn.datasets import fetch_openml


fashion_mnist = fetch_openml(name="Fashion-MNIST", as_frame=False) #as_frames = False for getting the numpy arrays instead of pandas dataframe/series
X = torch.FloatTensor(fashion_mnist.data.reshape(-1, 1, 28, 28) / 255.)
y = torch.from_numpy(fashion_mnist.target.astype(int))
in_B = (y == 0) | (y == 2)  # Pullover or T-shirt/top
X_A, y_A = X[~in_B], y[~in_B]
y_A = torch.maximum(y_A - 2, torch.tensor(0))  # [1,3,4,5,6,7,8,9] => [0,..,7]
X_B, y_B = X[in_B], (y[in_B] == 2).to(dtype=torch.float32).view(-1, 1)

train_set_A = TensorDataset(X_A[:-7_000], y_A[:-7000])
valid_set_A = TensorDataset(X_A[-7_000:-5000], y_A[-7000:-5000])
test_set_A = TensorDataset(X_A[-5_000:], y_A[-5000:])
train_set_B = TensorDataset(X_B[:20], y_B[:20])
valid_set_B = TensorDataset(X_B[20:5000], y_B[20:5000])
test_set_B = TensorDataset(X_B[5_000:], y_B[5000:])

train_loader_A = DataLoader(train_set_A, batch_size=32, shuffle=True)
valid_loader_A = DataLoader(valid_set_A, batch_size=32)
test_loader_A = DataLoader(test_set_A, batch_size=32)
train_loader_B = DataLoader(train_set_B, batch_size=32, shuffle=True)
valid_loader_B = DataLoader(valid_set_B, batch_size=32)
test_loader_B = DataLoader(test_set_B, batch_size=32)

In [45]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

device


'cpu'

'cpu'

In [46]:
%pip install torchmetrics


import torchmetrics

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric.update(y_pred, y_batch)
    return metric.compute()

def train(model, optimizer, loss_fn, metric, train_loader, valid_loader,
          n_epochs):
    history = {"train_losses": [], "train_metrics": [], "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.0
        metric.reset()
        model.train()
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            # Uncomment to activate gradient clipping:
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            optimizer.zero_grad()
            metric.update(y_pred, y_batch)
        history["train_losses"].append(total_loss / len(train_loader))
        history["train_metrics"].append(metric.compute().item())
        history["valid_metrics"].append(
            evaluate_tm(model, valid_loader, metric).item())
        print(f"Epoch {epoch + 1}/{n_epochs}, "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.4f}, "
              f"valid metric: {history['valid_metrics'][-1]:.4f}")
    return history



   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 16.7 MB/s eta 0:00:00


In [47]:
torch.manual_seed(42)

model_A = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28 * 28, 100),
    nn.ReLU(),
    nn.Linear(100, 100),
    nn.ReLU(),
    nn.Linear(100, 100),
    nn.ReLU(),
    nn.Linear(100, 8)
  )
model_A = model_A.to(device)

In [48]:
model_A.apply(use_he_init)

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=100, bias=True)
  (2): ReLU()
  (3): Linear(in_features=100, out_features=100, bias=True)
  (4): ReLU()
  (5): Linear(in_features=100, out_features=100, bias=True)
  (6): ReLU()
  (7): Linear(in_features=100, out_features=8, bias=True)
)

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=100, bias=True)
  (2): ReLU()
  (3): Linear(in_features=100, out_features=100, bias=True)
  (4): ReLU()
  (5): Linear(in_features=100, out_features=100, bias=True)
  (6): ReLU()
  (7): Linear(in_features=100, out_features=8, bias=True)
)

In [49]:
n_epochs = 20
optimizer = torch.optim.SGD(model_A.parameters(), lr=0.005)
loss_fn = nn.CrossEntropyLoss()
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=8).to(device)
history_A = train(model_A, optimizer, loss_fn, accuracy, train_loader_A, valid_loader_A, n_epochs )

Epoch 1/20, train loss: 0.8492, train metric: 0.7197, valid metric: 0.8120
Epoch 2/20, train loss: 0.4533, train metric: 0.8487, valid metric: 0.8620
Epoch 3/20, train loss: 0.3771, train metric: 0.8727, valid metric: 0.8685
Epoch 4/20, train loss: 0.3405, train metric: 0.8827, valid metric: 0.8890
Epoch 5/20, train loss: 0.3184, train metric: 0.8904, valid metric: 0.8825
Epoch 6/20, train loss: 0.3032, train metric: 0.8953, valid metric: 0.8880
Epoch 7/20, train loss: 0.2911, train metric: 0.8999, valid metric: 0.8910
Epoch 8/20, train loss: 0.2817, train metric: 0.9031, valid metric: 0.8960
Epoch 9/20, train loss: 0.2735, train metric: 0.9053, valid metric: 0.8985
Epoch 10/20, train loss: 0.2666, train metric: 0.9083, valid metric: 0.8900
Epoch 11/20, train loss: 0.2610, train metric: 0.9108, valid metric: 0.9025
Epoch 12/20, train loss: 0.2546, train metric: 0.9127, valid metric: 0.8985
Epoch 13/20, train loss: 0.2502, train metric: 0.9146, valid metric: 0.8860
Epoch 14/20, train lo

In [53]:
torch.manual_seed(42)
model_B = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28 * 28, 100),
    nn.ReLU(),
    nn.Linear(100, 100),
    nn.ReLU(),
    nn.Linear(100, 100),
    nn.ReLU(),
    nn.Linear(100, 1)
).to(device)

In [54]:
model_B.apply(use_he_init)

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=100, bias=True)
  (2): ReLU()
  (3): Linear(in_features=100, out_features=100, bias=True)
  (4): ReLU()
  (5): Linear(in_features=100, out_features=100, bias=True)
  (6): ReLU()
  (7): Linear(in_features=100, out_features=1, bias=True)
)

In [56]:
n_epochs = 20
optimizer = torch.optim.SGD(model_B.parameters(), lr=0.001)
loss_fn = nn.BCEWithLogitsLoss()
accuracy = torchmetrics.Accuracy(task="binary").to(device)
history_B = train(model_B, optimizer, loss_fn, accuracy, train_loader_B, valid_loader_B, n_epochs)

Epoch 1/20, train loss: 0.3079, train metric: 1.0000, valid metric: 0.8289
Epoch 2/20, train loss: 0.3065, train metric: 1.0000, valid metric: 0.8299
Epoch 3/20, train loss: 0.3051, train metric: 1.0000, valid metric: 0.8305
Epoch 4/20, train loss: 0.3037, train metric: 1.0000, valid metric: 0.8311
Epoch 5/20, train loss: 0.3023, train metric: 1.0000, valid metric: 0.8313
Epoch 6/20, train loss: 0.3010, train metric: 1.0000, valid metric: 0.8319
Epoch 7/20, train loss: 0.2996, train metric: 1.0000, valid metric: 0.8321
Epoch 8/20, train loss: 0.2982, train metric: 1.0000, valid metric: 0.8331
Epoch 9/20, train loss: 0.2969, train metric: 1.0000, valid metric: 0.8341
Epoch 10/20, train loss: 0.2955, train metric: 1.0000, valid metric: 0.8347
Epoch 11/20, train loss: 0.2942, train metric: 1.0000, valid metric: 0.8351
Epoch 12/20, train loss: 0.2928, train metric: 1.0000, valid metric: 0.8357
Epoch 13/20, train loss: 0.2914, train metric: 1.0000, valid metric: 0.8357
Epoch 14/20, train lo

In [57]:
# reusing all the layers except the output layer
import copy

torch.manual_seed(42)
reused_layer = copy.deepcopy(model_A[: -1])
model_B_on_A = nn.Sequential(
    *reused_layer,
    nn.Linear(100, 1) # new output layer for task B
).to(device)

Note:
- `copy.deepcopy()` function to copy all the modules and submodules in `nn.Sequential` module
- model_B_on_A is another `nn.Sequential` module based on the reused layers of model A plus a new output layer for task B it has a single output since task B is binary classification.

In [58]:
# freezing the reused layers during the first few epochs:
for layer in model_B_on_A[:-1]:
  for param in layer.parameters():
    param.requires_grad = False


In [63]:
n_epochs = 10
optimizer = torch.optim.SGD(model_B_on_A.parameters(), lr=0.005)
xentropy = nn.BCEWithLogitsLoss()
accuracy = torchmetrics.Accuracy(task="binary").to(device)
history_B = train(model_B_on_A, optimizer, xentropy, accuracy,
                  train_loader_B, valid_loader_B, n_epochs)

Epoch 1/10, train loss: 0.6172, train metric: 0.4000, valid metric: 0.5378
Epoch 2/10, train loss: 0.5871, train metric: 0.4500, valid metric: 0.5759
Epoch 3/10, train loss: 0.5609, train metric: 0.6500, valid metric: 0.6373
Epoch 4/10, train loss: 0.5385, train metric: 0.8000, valid metric: 0.7124
Epoch 5/10, train loss: 0.5201, train metric: 0.8500, valid metric: 0.7817
Epoch 6/10, train loss: 0.5055, train metric: 0.8500, valid metric: 0.8327
Epoch 7/10, train loss: 0.4945, train metric: 0.9000, valid metric: 0.8639
Epoch 8/10, train loss: 0.4863, train metric: 0.9000, valid metric: 0.8791
Epoch 9/10, train loss: 0.4794, train metric: 0.8500, valid metric: 0.8851
Epoch 10/10, train loss: 0.4729, train metric: 0.8500, valid metric: 0.8888


In [64]:
# unfreezing the reused layers during the first few epochs:
for layer in model_B_on_A[2:]:
  for param in layer.parameters():
    param.requires_grad = True

In [74]:
n_epochs = 20
optimizer = torch.optim.SGD(model_B_on_A.parameters(), lr=0.03)
xentropy = nn.BCEWithLogitsLoss()
accuracy = torchmetrics.Accuracy(task="binary").to(device)
history_B = train(model_B_on_A, optimizer, xentropy, accuracy,
                train_loader_B, valid_loader_B, n_epochs)

Epoch 1/20, train loss: 0.0674, train metric: 1.0000, valid metric: 0.9261
Epoch 2/20, train loss: 0.0409, train metric: 1.0000, valid metric: 0.9371
Epoch 3/20, train loss: 0.0312, train metric: 1.0000, valid metric: 0.9416
Epoch 4/20, train loss: 0.0264, train metric: 1.0000, valid metric: 0.9440
Epoch 5/20, train loss: 0.0235, train metric: 1.0000, valid metric: 0.9456
Epoch 6/20, train loss: 0.0215, train metric: 1.0000, valid metric: 0.9472
Epoch 7/20, train loss: 0.0200, train metric: 1.0000, valid metric: 0.9476
Epoch 8/20, train loss: 0.0190, train metric: 1.0000, valid metric: 0.9490
Epoch 9/20, train loss: 0.0181, train metric: 1.0000, valid metric: 0.9484
Epoch 10/20, train loss: 0.0175, train metric: 1.0000, valid metric: 0.9488
Epoch 11/20, train loss: 0.0169, train metric: 1.0000, valid metric: 0.9480
Epoch 12/20, train loss: 0.0165, train metric: 1.0000, valid metric: 0.9472
Epoch 13/20, train loss: 0.0161, train metric: 1.0000, valid metric: 0.9470
Epoch 14/20, train lo